
services:
  app:
    env_file: 
      - .env-docker.local
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Pass Cognito variables as build arguments
        NEXT_PUBLIC_COGNITO_REGION: ${NEXT_PUBLIC_COGNITO_REGION}
        NEXT_PUBLIC_COGNITO_USER_POOL_ID: ${NEXT_PUBLIC_COGNITO_USER_POOL_ID}
        NEXT_PUBLIC_COGNITO_APP_CLIENT_ID: ${NEXT_PUBLIC_COGNITO_APP_CLIENT_ID}
        NEXT_PUBLIC_COGNITO_IDENTITY_POOL_ID: ${NEXT_PUBLIC_COGNITO_IDENTITY_POOL_ID}
    image: postgres-table-app:latest
    ports:
      - "3000:3000"
    networks:
      - pgbrowse-net
    environment:
      # Runtime environment variables (for server-side code)
      - NODE_ENV=production
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    restart: unless-stopped

networks:
   pgbrowse-net:
     name: pgbrowse-net
     external: true
    